"""Resource-scoped sandbox contracts.

C11-C widens the canonical C08 *capability* contract into a *resource-scoped
authorization contract* and adds the deterministic per-Attempt enforcement
boundary.  See :mod:`saberops.sandbox.grants`,
:mod:`saberops.sandbox.policy`, and
:mod:`saberops.sandbox.exposure`.
"""

from saberops.sandbox.enforcement import (
    FILESYSTEM_CONTAINMENT_UNAVAILABLE_MESSAGE,
    NATIVE_STRUCTURED_ADAPTER_SOURCES,
    NATIVE_STRUCTURED_VERIFIED_SOURCES,
    READONLY_CONTAINMENT_UNAVAILABLE_MESSAGE,
    RUNTIME_READONLY_BINDS,
    AutonomousDispatchPreflight,
    BoundaryEvidence,
    SandboxEffectInterceptor,
    SandboxEnforcementBackend,
    SandboxEnforcementCapability,
    SandboxEnforcementError,
    VerifiedTraceMechanism,
    attach_sandbox_interceptor,
    audit_changed_paths,
    backend_capabilities,
    boundary_evidence_for,
    bwrap_available,
    bwrap_mount_args_for_policy,
    deny_mask_paths,
    empty_mask_dir,
    ensure_sandbox_bind_dirs,
    filesystem_containment_available,
    policy_is_mutating,
    policy_is_repo_writable,
    preflight_as_dict,
    preflight_autonomous_dispatch,
    preflight_executable,
    preflight_write,
    readable_bind_paths,
    record_intercepted_effect,
    require_exact_writable_scope,
    require_installed_trace_mechanism,
    resolve_trace_capability,
    resolve_within_repo,
    retire_boundary_installation,
    runtime_readonly_binds,
    verify_native_trace_source,
    writable_bind_dirs,
    writable_scope_violation,
)
from saberops.sandbox.exposure import (
    ExposureEntry,
    ExposureMechanism,
    ToolExposurePlan,
)
from saberops.sandbox.grants import (
    CapabilityEntry,
    CapabilityOperation,
    PathPattern,
    ResourceScope,
    SandboxContractError,
    SideEffectSemantics,
    ToolGrant,
    c08_to_runtime_side_effect,
    validate_credential_ref,
)
from saberops.sandbox.policy import (
    GIT_INTERNAL_DENY,
    GITHUB_DENY,
    NetworkPolicy,
    ProcessPolicy,
    ResourceLimits,
    SandboxPolicy,
    default_sandbox_policy,
    grant_for_sandbox,
)

__all__ = [
    "AutonomousDispatchPreflight",
    "BoundaryEvidence",
    "CapabilityEntry",
    "CapabilityOperation",
    "ExposureEntry",
    "ExposureMechanism",
    "FILESYSTEM_CONTAINMENT_UNAVAILABLE_MESSAGE",
    "GIT_INTERNAL_DENY",
    "GITHUB_DENY",
    "NATIVE_STRUCTURED_ADAPTER_SOURCES",
    "NATIVE_STRUCTURED_VERIFIED_SOURCES",
    "NetworkPolicy",
    "PathPattern",
    "ProcessPolicy",
    "READONLY_CONTAINMENT_UNAVAILABLE_MESSAGE",
    "RUNTIME_READONLY_BINDS",
    "ResourceLimits",
    "ResourceScope",
    "SandboxContractError",
    "SandboxEffectInterceptor",
    "SandboxEnforcementBackend",
    "SandboxEnforcementCapability",
    "SandboxEnforcementError",
    "SandboxPolicy",
    "SideEffectSemantics",
    "ToolExposurePlan",
    "ToolGrant",
    "VerifiedTraceMechanism",
    "attach_sandbox_interceptor",
    "audit_changed_paths",
    "backend_capabilities",
    "boundary_evidence_for",
    "bwrap_available",
    "bwrap_mount_args_for_policy",
    "c08_to_runtime_side_effect",
    "default_sandbox_policy",
    "deny_mask_paths",
    "empty_mask_dir",
    "ensure_sandbox_bind_dirs",
    "filesystem_containment_available",
    "grant_for_sandbox",
    "policy_is_mutating",
    "policy_is_repo_writable",
    "preflight_as_dict",
    "preflight_autonomous_dispatch",
    "preflight_executable",
    "preflight_write",
    "readable_bind_paths",
    "record_intercepted_effect",
    "require_exact_writable_scope",
    "require_installed_trace_mechanism",
    "resolve_trace_capability",
    "resolve_within_repo",
    "retire_boundary_installation",
    "runtime_readonly_binds",
    "verify_native_trace_source",
    "writable_bind_dirs",
    "writable_scope_violation",
    "validate_credential_ref",
]
