"""C11 Project Ledger: durable Project authority and cross-session continuity.

    Project Ledger -> Orch N -> deterministic checkpoint -> verified durable
    delta -> Orch N+1 reconstructs a bounded bootstrap

The Project owns authoritative state.  Orch sessions are disposable and their
context is a cache, never memory.  Continuity succeeds when the next Orch can
make equivalent Project decisions from durable state alone -- without the
predecessor's transcript, process, provider or model.
"""

from orchestrator_mvp.project_ledger.bootstrap import build_bootstrap, resume_project
from orchestrator_mvp.project_ledger.checkpoint import (
    VerifiedCheckpoint,
    build_checkpoint,
    create_checkpoint,
    latest_verified_checkpoint,
    load_checkpoint,
    verify_checkpoint,
)
from orchestrator_mvp.project_ledger.continuity import runtime_composition
from orchestrator_mvp.project_ledger.contracts import (
    BOOTSTRAP_SCHEMA_VERSION,
    CHECKPOINT_SCHEMA_VERSION,
    LEDGER_SCHEMA_VERSION,
    BootstrapBudget,
    ChangeIntake,
    CheckpointAncestryError,
    CheckpointDigestError,
    CheckpointStateMismatchError,
    FactCategory,
    InFlightWork,
    IntakeDisposition,
    LedgerEvent,
    LedgerEventType,
    OpenQuestion,
    OrchBootstrap,
    ProjectCheckpoint,
    ProjectDecision,
    ProjectFact,
    ProjectIdentityMismatchError,
    ProjectIdentityRecord,
    ProjectLedgerCommandError,
    ProjectLedgerConflictError,
    ProjectLedgerError,
    ProjectLedgerIntegrityError,
    ProjectLedgerNotFoundError,
    ProjectOrigin,
    ProjectState,
    Provenance,
    QuestionStatus,
    RecordOrigin,
    RecordStatus,
    RoadmapItem,
    RoadmapStatus,
    RuntimeComposition,
    UnsupportedSchemaVersionError,
    canonical_json,
    digest_of,
)
from orchestrator_mvp.project_ledger.genesis import (
    InferredAssumption,
    ProjectBootstrapResult,
    create_project,
    takeover_project,
)
from orchestrator_mvp.project_ledger.inspection import project_ledger_snapshot
from orchestrator_mvp.project_ledger.observation import (
    ObservedFile,
    RepositoryObservation,
    assert_project_repository,
    observe_repository,
)
from orchestrator_mvp.project_ledger.store import ProjectLedger, load_project, read_project_state

__all__ = [
    "BOOTSTRAP_SCHEMA_VERSION",
    "CHECKPOINT_SCHEMA_VERSION",
    "LEDGER_SCHEMA_VERSION",
    "BootstrapBudget",
    "ChangeIntake",
    "CheckpointAncestryError",
    "CheckpointDigestError",
    "CheckpointStateMismatchError",
    "FactCategory",
    "InFlightWork",
    "InferredAssumption",
    "IntakeDisposition",
    "LedgerEvent",
    "LedgerEventType",
    "ObservedFile",
    "OpenQuestion",
    "OrchBootstrap",
    "ProjectBootstrapResult",
    "ProjectCheckpoint",
    "ProjectDecision",
    "ProjectFact",
    "ProjectIdentityMismatchError",
    "ProjectIdentityRecord",
    "ProjectLedger",
    "ProjectLedgerCommandError",
    "ProjectLedgerConflictError",
    "ProjectLedgerError",
    "ProjectLedgerIntegrityError",
    "ProjectLedgerNotFoundError",
    "ProjectOrigin",
    "ProjectState",
    "Provenance",
    "QuestionStatus",
    "RecordOrigin",
    "RecordStatus",
    "RepositoryObservation",
    "RoadmapItem",
    "RoadmapStatus",
    "RuntimeComposition",
    "UnsupportedSchemaVersionError",
    "VerifiedCheckpoint",
    "assert_project_repository",
    "build_bootstrap",
    "build_checkpoint",
    "canonical_json",
    "create_checkpoint",
    "create_project",
    "digest_of",
    "latest_verified_checkpoint",
    "load_checkpoint",
    "load_project",
    "observe_repository",
    "project_ledger_snapshot",
    "read_project_state",
    "resume_project",
    "runtime_composition",
    "takeover_project",
    "verify_checkpoint",
]
